[package]
name = "stegosaurus"
version = "0.1.0"
edition = "2021"
author = "andreasduerloo@gmail.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
